CREATE TABLE ACTOR(
    id VARCHAR(36) NOT NULL,
    name VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    description VARCHAR(400) NOT NULL,
    created_at DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY(
    id VARCHAR(36) NOT NULL,
    name VARCHAR UNIQUE NOT NULL,
    PRIMARY KEY (id)
);